### ISSUE TITLE
Первичное изучение кода

### ISSUE THREAD

**Issue by ioannkozlitin** [Artemmkin/ion3#1]
"Глянул еще повнимательнее ваши комментарии. Скажите, а в вашей диссертации формулы как-то помечаются цифрами? Вы отсылаете к формуле (25), но найти такое обозначение формулы я не могу. В диссертации постоянно идут отсылки вот такого вида [33], я не очень понимаю смысл этих цифр и на что они ссылаются. Поясните, пожалуйста, если не трудно.  P.S. я кажется догадался, что за формула 25 - та, что на странице 42, где еще высчитываетя fk*(xe). Но все-таки для дальнейшей работы хотелось бы понимать, что означают  цифры внутри квадратных скобок. 

Еще Иван Алексеевич напишите, пожалуйста, задание того, что нужно будет сделать. У меня будет время на этих выходных, и я надеялся доразбираться с кодом и, возможно, уже начать работать над самой задачей. "

Я ссылаюсь здесь на автореферат. Если написано (25) - то это нумерованная формула под номером 25 (номер указывается справа от формулы), если [25] - то это книга или статья из списка литературы под тем же номером 25.

**Comment by Artemmkin** [comment]
Добавил еще несколько вопросов касательно функций кода

**Comment by ioannkozlitin** [comment]
Как успехи? Есть ко мне вопросы? Желательно конкретные.

**Comment by ioannkozlitin** [comment]
Диссер мой все-таки перегоните в pdf и закиньте в theory

**Comment by Artemmkin** [comment]
Пока вопросов нету, на этой неделе доразбираюсь и вам отпишусь. Диссертацию добавил.

**Comment by ioannkozlitin** [comment]
Спасибо!

**Comment by Artemmkin** [comment]
Иван Алексеевич, поясните, пожалуйста, следующий момент. В левой части уравнения Саха, присутствует слагаемое "дельта фи", которое считается по формуле (22). Не понятно где взять "дельта F" в формуле (22). И нужно ли учитывать слагаемое "дельта(круглое) фи", которое считается по формуле (23)

**Comment by ioannkozlitin** [comment]
Круглые учитывать не надо. "дельта F" берем из статьи (см. формулу (7)), там оно равно P(v_k-v_{k-1}).

**Comment by Artemmkin** [comment]
Иван Алексеевич, написал функцию sahaleft. Посмотрите, пожалуйста, это ли требовалось сделать и таким ли образом. Там на выводе первые три числа получаются далекими от равенства нулю, вследствие того что _x[i] получаются равными нулю и логарифм от нуля нормально не возьмешь.

**Comment by ioannkozlitin** [comment]
В принципе все правильно, но есть одно существенное замечание: вместо res.M, res.P подставить mu(T, vFree, xe) и p(T,vFree, xe) соответственно. При этом xe берем как sum(_x[i]*i) из балансного соотношения, vFree (пока!) считаем как Vfree(V, xe), T и V надо передавать как параметры (каюсь, не заметил), не забыв перевести к нужным единицам, res передавать не надо, так как во время расчета мы его еще не будем иметь в распоряжении (в этом вся загвоздка).

Еще вопрос: зачем Вы скопировали к себе все исходники? Может лучше ветку сделать?

**Comment by Artemmkin** [comment]
Хорошо, я понял, сегодня вечером переделаю. Я создал  папку diplom - это просто проект, который я создал в codeblocks. Думаю не стоит создавать отдельную ветку для этого. Буду работать в данном проекте и переносить изменения в остальные файлы для вас.

**Comment by ioannkozlitin** [comment]
Ну если Вам так удобнее... А Вы сами не запутаетесь? Впрочем, дело ваше...
